import { Event } from '@/lib/types';

const catalogCreatedAt = '2026-02-26T00:00:00+05:30';

export const EVENT_CATALOG: Event[] = [
    {
        id: '10000000-0000-0000-0000-000000000001',
        name: 'CodeStorm',
        slug: 'codestorm',
        description: 'Competitive programming challenge. Solve complex algorithmic problems under time pressure.',
        long_description: null,
        category: 'technical',
        fee: 15000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-15 10:00:00+05:30',
        registration_deadline: null,
        venue: 'Computer Lab 1',
        rules: ['Individual participation', 'Duration: 2 hours', 'Languages: C, C++, Java, Python'],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000002',
        name: 'HackNova',
        slug: 'hacknova',
        description: '24-hour hackathon to build innovative solutions for real-world problems.',
        long_description: null,
        category: 'technical',
        fee: 40000,
        fee_calculation: 'per_team',
        max_participants: 300,
        current_participants: 0,
        event_date: '2026-03-15 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Main Auditorium',
        rules: ['Team size: 2-4 members', 'Duration: 24 hours', 'Bring your own laptops'],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 4,
        team_size_fixed: null,
        team_size_min: 2,
        team_size_max: 4,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000003',
        name: 'RoboWars',
        slug: 'robowars',
        description: 'Battle of robots! Design, build, and fight your robot against competitors.',
        long_description: null,
        category: 'technical',
        fee: 50000,
        fee_calculation: 'per_team',
        max_participants: 250,
        current_participants: 0,
        event_date: '2026-03-16 11:00:00+05:30',
        registration_deadline: null,
        venue: 'Sports Ground',
        rules: ['Team size: 2-5 members', 'Robot weight limit: 25kg', 'Safety gear mandatory'],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 5,
        team_size_fixed: null,
        team_size_min: 2,
        team_size_max: 5,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000004',
        name: 'WebCraft',
        slug: 'webcraft',
        description: 'Web development competition. Build a responsive website in limited time.',
        long_description: null,
        category: 'technical',
        fee: 10000,
        fee_calculation: 'per_team',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-16 10:00:00+05:30',
        registration_deadline: null,
        venue: 'Computer Lab 2',
        rules: ['Individual or team of 2', 'Duration: 4 hours', 'Frameworks allowed'],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 2,
        team_size_fixed: null,
        team_size_min: 1,
        team_size_max: 2,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000005',
        name: 'DebugDash',
        slug: 'debugdash',
        description: 'Find and fix bugs in code snippets across multiple languages.',
        long_description: null,
        category: 'technical',
        fee: 10000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-15 14:00:00+05:30',
        registration_deadline: null,
        venue: 'Computer Lab 1',
        rules: ['Individual participation', 'Duration: 1.5 hours', 'Languages: C, Java, Python'],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000006',
        name: 'Rhythmix',
        slug: 'rhythmix',
        description: 'Group dance competition. Showcase your choreography and stage presence.',
        long_description: null,
        category: 'cultural',
        fee: 30000,
        fee_calculation: 'per_team',
        max_participants: 300,
        current_participants: 0,
        event_date: '2026-03-15 18:00:00+05:30',
        registration_deadline: null,
        venue: 'Main Stage',
        rules: ['Team size: 5-15 members', 'Duration: 5-8 minutes'],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 15,
        team_size_fixed: null,
        team_size_min: 5,
        team_size_max: 15,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000007',
        name: 'Sargam',
        slug: 'sargam',
        description: 'Solo singing competition. Any genre, any language.',
        long_description: null,
        category: 'cultural',
        fee: 10000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-16 15:00:00+05:30',
        registration_deadline: null,
        venue: 'Seminar Hall',
        rules: ['Solo participation', 'Duration: 4-6 minutes'],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000008',
        name: 'Natya',
        slug: 'natya',
        description: 'Street play / Nukkad Natak with socially relevant themes.',
        long_description: null,
        category: 'cultural',
        fee: 20000,
        fee_calculation: 'per_team',
        max_participants: 300,
        current_participants: 0,
        event_date: '2026-03-16 11:00:00+05:30',
        registration_deadline: null,
        venue: 'Open Air Theatre',
        rules: ['Team size: 8-20 members', 'Duration: 10-15 minutes'],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 20,
        team_size_fixed: null,
        team_size_min: 8,
        team_size_max: 20,
        created_at: catalogCreatedAt,
    },
    {
        id: '10000000-0000-0000-0000-000000000009',
        name: 'Lens & Frame',
        slug: 'lens-frame',
        description: 'Photography contest to capture the essence of the fest.',
        long_description: null,
        category: 'cultural',
        fee: 5000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-15 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Entire Campus',
        rules: ['Individual participation', 'DSLR or mobile allowed', 'Submit best shots'],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000001',
        name: 'Badminton',
        slug: 'badminton',
        description: 'Outdoor badminton event under Manthan Sports Committee.',
        long_description: null,
        category: 'sports',
        fee: 30000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-15 09:00:00+05:30',
        registration_deadline: null,
        venue: 'Sports Court',
        rules: [
            'Service must be underarm.',
            'Shuttle must be below the waist.',
            'Both feet must stay inside the service court.',
            'If player\'s score is even (0,2,4…) serve from right side.',
            'If score is odd (1,3,5…) serve from left side.',
            'Fault: shuttle lands outside boundary line.',
            'Fault: shuttle hits net and does not cross.',
            'Fault: player touches the net.',
            'Fault: shuttle touches player\'s body.',
            'Fault: double hit or illegal stroke.',
        ],
        prize_text: 'Winner: ₹1,000 | Runner Up: ₹600',
        prize_winner: 100000,
        prize_runner_up: 60000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000002',
        name: 'Box Cricket',
        slug: 'box-cricket',
        description: 'Box cricket tournament under Manthan Sports Committee.',
        long_description: null,
        category: 'sports',
        fee: 100000,
        fee_calculation: 'per_team',
        max_participants: 300,
        current_participants: 0,
        event_date: '2026-03-15 08:00:00+05:30',
        registration_deadline: null,
        venue: 'Cricket Ground',
        rules: [
            'Team size: 6 to 8 players.',
            'Only 6 players are allowed on the field at a time.',
            'Minimum 5 players are required to start the match.',
            'Substitutions are allowed only between overs with umpire permission.',
            'Match format: 5 to 10 overs per side as decided before match.',
            'Each bowler can bowl max 1 over in a 5-over match or 2 overs in a 10-over match.',
            'Underarm or overarm bowling is allowed as per tournament rule.',
            'Toss decides batting or bowling; visiting team calls toss.',
            'Dismissals: bowled, caught, run out, stumped, hit wicket.',
            'Umpire decision is final and binding.',
        ],
        prize_text: 'Winner: ₹6,000 | Runner Up: ₹3,000',
        prize_winner: 600000,
        prize_runner_up: 300000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 8,
        team_size_fixed: null,
        team_size_min: 6,
        team_size_max: 8,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000003',
        name: 'Volleyball',
        slug: 'volleyball',
        description: 'Volleyball competition under Manthan Sports Committee.',
        long_description: null,
        category: 'sports',
        fee: 70000,
        fee_calculation: 'per_team',
        max_participants: 300,
        current_participants: 0,
        event_date: '2026-03-16 08:00:00+05:30',
        registration_deadline: null,
        venue: 'Volleyball Court',
        rules: [
            'College ID card is compulsory for every participant.',
            '6 players on the court at one time: 3 front row and 3 back row.',
            'Maximum 3 hits per side.',
            'Rally-point scoring: points are made on every serve for the rally-winning team.',
            'A player may not hit the ball twice in succession (block is not counted as a hit).',
            'Ball may be played off the net during a volley and on serve.',
            'Ball is out if it hits antenna/net post, floor completely outside court, net/cables outside antenna, referee stand/pole, or ceiling above nonplayable area.',
            'It is legal to contact the ball with any part of a player\'s body.',
            'It is illegal to catch, hold, or throw the ball.',
            'A player cannot block or attack a serve from on or inside the 10-foot line.',
            'After the serve, front-line players may switch positions at the net.',
            'Matches are made up of sets as per level of play.',
            '3-set matches are of 15 points.',
            'Each set must be won by two points; winner is first team to win 2 sets.',
        ],
        prize_text: 'Winner: ₹3,000 | Runner Up: ₹1,500',
        prize_winner: 300000,
        prize_runner_up: 150000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 8,
        team_size_fixed: 8,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000004',
        name: 'Tug of war',
        slug: 'tug-of-war',
        description: 'Tug of war challenge under Manthan Sports Committee.',
        long_description: null,
        category: 'sports',
        fee: 50000,
        fee_calculation: 'per_team',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-16 10:00:00+05:30',
        registration_deadline: null,
        venue: 'Main Ground',
        rules: [
            'Team size: 8 players per team.',
            'Two teams compete against each other.',
            'College ID is compulsory for all participants.',
            'A long rope is used with a centre mark aligned over the ground center line.',
            'Objective: pull the opposing team so the centre mark crosses your side boundary line.',
            'Players hold the rope with hands only.',
            'Teams start pulling only on referee signal.',
            'Foul: sitting or lying down while pulling.',
            'Foul: wrapping rope around body or arm.',
            'Foul: sudden jerks before signal.',
            'Foul: using gloves.',
        ],
        prize_text: 'Winner: ₹1,800 | Runner Up: ₹1,000',
        prize_winner: 180000,
        prize_runner_up: 100000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 8,
        team_size_fixed: 8,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000005',
        name: 'Chess',
        slug: 'chess',
        description: 'Chess tournament under Manthan Sports Committee.',
        long_description: null,
        category: 'sports',
        fee: 20000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-15 11:00:00+05:30',
        registration_deadline: null,
        venue: 'Indoor Hall',
        rules: [
            'Game time is 15 minutes.',
            'Black and white sides are decided 2 minutes before game by coin toss.',
            'First touch move rule applies: if a player touches a piece, that piece must be moved.',
            'If a player moves a different piece than first touched: first time warning, second time disqualification.',
            'No phones, digital watches, or smart devices are allowed.',
            'No talking is allowed during the game.',
            'All games are knockout games.',
            'Illegal move policy: first illegal move warning, second illegal move loss of game.',
            'Draw conditions: stalemate, insufficient material, or same move repeated 3 times.',
            'After draw: blitz playoff (5 minutes each).',
            'If still draw: White gets 5 minutes, Black gets 4 minutes, and Black wins if draw again.',
            'No external assistance is allowed.',
            'No distracting behavior is allowed.',
            'If a player disrupts the chess board, that player is disqualified.',
            'College ID is compulsory.',
        ],
        prize_text: 'Winner: ₹800 | Runner Up: ₹400',
        prize_winner: 80000,
        prize_runner_up: 40000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000006',
        name: 'Carrom',
        slug: 'carrom',
        description: 'Carrom tournament under Manthan Sports Committee.',
        long_description: null,
        category: 'sports',
        fee: 20000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-15 12:00:00+05:30',
        registration_deadline: null,
        venue: 'Indoor Hall',
        rules: [
            'College I-card is compulsory.',
            'Using thumb is not allowed.',
            'Toss/coin flip decides who starts first; toss winner chooses white or black coins.',
            'Queen must be pocketed first and covered by pocketing one of your own coins in the next shot.',
            'If queen is not covered, it is returned to the center.',
            'Scoring: each coin = 1 point, queen = 3 points.',
            'Foul: striker is pocketed.',
            'Foul: pocketing opponent\'s coins.',
            'Foul: striker leaves the board.',
            'Foul: touching a coin with hand.',
        ],
        prize_text: 'Winner: ₹800 | Runner Up: ₹400',
        prize_winner: 80000,
        prize_runner_up: 40000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000007',
        name: 'Ludo',
        slug: 'ludo',
        description: 'Ludo competition under Manthan Sports Committee.',
        long_description: null,
        category: 'sports',
        fee: 3000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-16 11:00:00+05:30',
        registration_deadline: null,
        venue: 'Indoor Hall',
        rules: [
            'Tournament format: single-elimination knockout.',
            'Each match consists of 4 players per board.',
            'Only 1st position advances to next round.',
            'Final winner is declared champion.',
            'Ideal participant counts: 16, 32, 64; qualifiers may be used for uneven numbers.',
            'Players are assigned randomly with no color preference.',
            'Equipment: standard Ludo board, one six-faced dice, and four tokens per player.',
            'A player must roll 6 to bring a token out of home.',
            'Rolling 6 grants one additional turn.',
            'Rolling three consecutive 6s forfeits the turn.',
            'Tokens move clockwise.',
            'A token must complete a full round before entering the home column.',
            'An exact dice number is required to enter the final home triangle.',
            'If no valid move is available, the turn is skipped.',
            'Landing on an opponent\'s single token sends it back to home (capture).',
            'Capturing grants one additional turn.',
            'Tokens on safe squares (star-marked) cannot be captured.',
            'Two tokens of the same color on one square form a block.',
            'Blocks cannot be passed or captured and may be broken voluntarily by the player.',
            'Starting squares of each color are considered safe zones.',
            'Standard match duration is maximum 30 minutes.',
            'If time expires, ranking order: completed tokens, total distance covered, captures made, then sudden-death single-token race.',
            'Winner is the player who brings all four tokens home first.',
            'If tied: highest completed tokens, then highest captures, then single-token sudden death, then dice roll-off.',
            'Dice must be rolled within designated board area; cocked dice must be re-rolled.',
            'No interference with opponent tokens is allowed.',
            'Unsportsmanlike behavior leads to warning then disqualification.',
            'Referee decision is final.',
            'Referee supervises gameplay, maintains score sheet, enforces time, and may disqualify for misconduct.',
            'Disqualification grounds: repeated rule violations, physical interference, unfair practices, or verbal misconduct.',
            'Final round may be without time restriction or best of 3 matches.',
            'Champion title: College Ludo Champion – [Year].',
        ],
        prize_text: null,
        prize_winner: null,
        prize_runner_up: null,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000008',
        name: 'BGMI',
        slug: 'bgmi',
        description: 'BGMI e-sports competition under Manthan Sports Committee.',
        long_description: null,
        category: 'sports',
        fee: 40000,
        fee_calculation: 'per_team',
        max_participants: 300,
        current_participants: 0,
        event_date: '2026-03-16 12:00:00+05:30',
        registration_deadline: null,
        venue: 'E-Sports Arena',
        rules: [
            'I-card is compulsory.',
            'Only mobile devices are allowed.',
            'Only registered players can compete for one team at a time.',
            'No cheating, hacking, scripts, or third-party software is allowed.',
            'Teaming with other squads outside the rules is prohibited.',
            'No abusive or offensive behavior is allowed; maintain sportsmanship.',
            'College does not provide devices or accessories like chargers or earphones; carry your own.',
            'Reach the venue at least 30 minutes before the given time.',
            'Tournament official decisions are final.',
            'Late joining for matches is not allowed.',
            'Presence at the venue is mandatory.',
        ],
        prize_text: 'Winner: ₹4,000 | Runner Up: ₹2,500',
        prize_winner: 400000,
        prize_runner_up: 250000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 4,
        team_size_fixed: 4,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000009',
        name: 'Deadlift',
        slug: 'deadlift',
        description: 'Deadlift competition under Manthan Sports Committee.',
        long_description: null,
        category: 'sports',
        fee: 10000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-16 13:00:00+05:30',
        registration_deadline: null,
        venue: 'Fitness Arena',
        rules: ['Individual event', 'Weight category rules apply', 'Organizer decision is final'],
        prize_text: 'Winner: ₹1,000 | Runner Up: ₹400',
        prize_winner: 100000,
        prize_runner_up: 40000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
    {
        id: '20000000-0000-0000-0000-000000000010',
        name: 'Bench Press',
        slug: 'bench-press',
        description: 'Bench press competition under Manthan Sports Committee.',
        long_description: null,
        category: 'sports',
        fee: 10000,
        fee_calculation: 'per_participant',
        max_participants: 200,
        current_participants: 0,
        event_date: '2026-03-16 14:00:00+05:30',
        registration_deadline: null,
        venue: 'Fitness Arena',
        rules: ['Individual event', 'Weight category rules apply', 'Organizer decision is final'],
        prize_text: 'Winner: ₹1,000 | Runner Up: ₹400',
        prize_winner: 100000,
        prize_runner_up: 40000,
        prize_second_runner_up: null,
        image_url: null,
        is_active: true,
        team_size: 1,
        team_size_fixed: 1,
        team_size_min: null,
        team_size_max: null,
        created_at: catalogCreatedAt,
    },
];

export function getActiveEvents(): Event[] {
    return EVENT_CATALOG
        .filter((event) => event.is_active)
        .sort((a, b) => new Date(a.event_date).getTime() - new Date(b.event_date).getTime());
}

export function getEventById(eventId: string): Event | undefined {
    return EVENT_CATALOG.find((event) => event.id === eventId && event.is_active);
}

export function getEventBySlug(slug: string): Event | undefined {
    return EVENT_CATALOG.find((event) => event.slug === slug && event.is_active);
}

export function getEventsByIds(eventIds: string[]): Event[] {
    const idSet = new Set(eventIds);
    return getActiveEvents().filter((event) => idSet.has(event.id));
}
